    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://eureka-server-autg.azurewebsites.net/eureka

server:
  port: 8002
#  servlet:
#    context-path: /v1/register/

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: 'register'
    